name: Build and deploy Node.js app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless

      - name: Build for production
        run: npm run build --configuration=production

      - name: Create server.js for Azure
        run: |
          cat << 'EOF' > server.js
          const express = require('express');
          const path = require('path');
          const app = express();
          
          app.use(express.static(path.join(__dirname, 'dist/my-angular-app')));
          
          app.get('*', (req, res) => {
            res.sendFile(path.join(__dirname, 'dist/my-angular-app/index.html'));
          });
          
          const port = process.env.PORT || 8080;
          app.listen(port, () => {
            console.log(`Server running on port ${port}`);
          });
          EOF

      - name: Update package.json for Azure
        run: |
          npm install express --save
          node -e "
          const pkg = require('./package.json');
          pkg.scripts.start = 'node server.js';
          require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2));
          "

      - name: Zip artifact for deployment
        run: zip -r release.zip . -x "*.git*" "node_modules/*" "src/*" "e2e/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'frontend-demo-12'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FRONTEND }}
          package: .